### ISSUE TITLE
COACH DIES DELAYED

### ISSUE THREAD

**Issue by s-balint** [CHR15cs/CS2-Practice-Plugin#16]
hi, can you perhaps fix, that coach dies delayed? now he could throw some insta smokes from spawn if someone gives him smoke.

Also, I dont know this exactly but, can you somehow make it so coaches spawn in air, or in non competitive spawns? with setpos or smth, pracc.com plugins have this.

**Comment by CHR15cs** [comment]
I will look into it, should be an easy fix

**Comment by s-balint** [comment]
Thank you very much. I would appreciate if you could update me on the situation.

**Comment by CHR15cs** [comment]
I cannot reproduce the issue with the delayed kill, I will add the spawn outside the map but have to look deeper into the delayed kill issue

**Comment by s-balint** [comment]
If its outside the map, i think its even better tbh, would appricate that update. That way there is no spawn blocking and its the easiest solution I think.

**Comment by s-balint** [comment]
Also Is there a way to have more then 1 coaches in one team?

**Comment by CHR15cs** [comment]
> Also Is there a way to have more then 1 coaches in one team?

In the current version only 1 coach per team is allowed. I can change this to allow multiple coaches per team.

**Comment by s-balint** [comment]
Can you do that? i dont really need it now, but i might be useful for someone else, and it wouldnt be game breaking if you can figure out spawns outside of map.

**Comment by s-balint** [comment]
I was thinking, we didnt play actual matches on the plugin, but can the coach get the bomb? if yes its probably bad idea to spawn outside the map.

**Comment by CHR15cs** [comment]
I appreciate your feedback, yesterday evening I noticed the same issue.
Just tell me anything you think should be changed or you want added and I will try my best to implement it.
The next release will probably still take a while because we are changing stuff in the background which broke some stuff.

**Comment by s-balint** [comment]
I think you should  push the coaching update asap. 

Other than that .last on the practice mode would be nice, so it teleports you back to the last thrown grenade position. 
And a dryrun function on the practice mode, so you can dry run tactics with normal settings.

Ill make some ideas probably after we will actually play some scrims.

**Comment by CHR15cs** [comment]
I`ll open a new issue for the dry run mode, I`m already working on it.

If I get a somewhat stable state working then I can do a release but I currently have a huge problem with de-registring event hooks, I dont know if this is because of a CSSharp update or it never worked as intented, but this would be a show stopper, so its my highest priority right now

Feel free to open new issues for each of your idea, so we can have a good overview of the todo list
