### ISSUE TITLE
.Replay

### ISSUE THREAD

**Issue by eXeCutieTTV** [CHR15cs/CS2-Practice-Plugin#41]
If it isnt too much trouble, could you add the .replay commands as they were in the csgo plugin?
they were really handy, and i miss them:/

https://github.com/splewis/csgo-practice-mode#bot-replay-commands

**Comment by CHR15cs** [comment]
Sure, will try to do it.
Currently my priority is .throw / rethrow as soon as its done I will work on it.

**Comment by eXeCutieTTV** [comment]
thanks alot man!

**Comment by CHR15cs** [comment]
Do you have a video or something like that where I can see what exactly the plugin is doing on the server?
I havent used these features myself in the past so I dont know what to recreate exactly.

**Comment by eXeCutieTTV** [comment]
I can try to look in my documents, but dont get your hopes up.

But in terms Of what happens when you run the command.
Firstly a menu pops up wherein you can choose to either browse savede
replays, record a new replay, and some other stuff.
When you go into the record replay part you can record five POVS, and when
you have finished that, and play the replay, five Boys join the server and
replicate each POV simultaniously.
This is really usefull when showing Of an idea for an execute when praccing
with a team.

man. 15. jan. 2024 19.20 skrev CHR15cs ***@***.***>:

**Comment by eXeCutieTTV** [comment]
the csgo plugin can be found here; https://github.com/splewis/csgo-practice-mode#bot-replay-commands

I could sadly not find any useful videos for reference though:/

**Comment by CHR15cs** [comment]
I have some troubles replicating this, because some stuff that was used doing this in csgo doesnt exist yet, like OnPlayerCmd...
So my current development state can record positioning and grenade usage
But replaying this stuff does look very ugly since I just teleport the bots frame by frame through the server
But for now something like shooting, dropping weapons etc. is not implemented and I at least for now have no idea on how to implement it.
As soon as Im happy with the current implementation, I will record a small video on how to use it.
I am going to improve it over the time, but for now I think its the best I can offer you :(

**Comment by CHR15cs** [comment]
As soon as I know how to implement the other stuff, I will create a new issue for it.
The basic version of bot_mimic is released here:
https://github.com/CHR15cs/CS2-Practice-Plugin/releases/tag/v1.0.0.0
